## Alex Barbosa - 20/04/2024
 ### Curso de Python - Analise de Dados com Pandas e Numpy
 - Manipulação de Dados Pandas - Analise de Dados
 
 https://www.youtube.com/watch?v=FZODEbfcDwU

In [11]:
# Importando a Biblioteca - Pandas
import pandas as pd
import numpy as np

In [12]:
# Carregar dados de um arquivo csv
df = pd.read_csv('dados/df_vendas.csv')
df_lojas = pd.read_csv('dados/df_Lojas.csv')
df_produtos = pd.read_csv('dados/df_Produtos.csv')

In [13]:
# Visualizando dados das novas bases
df_lojas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Numero da loja   50 non-null     int64
 1   Nome da loja     50 non-null     object
 2   Cidade           50 non-null     object
 3   Estado           50 non-null     object
 4   Canal de vendas  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

In [14]:
df_lojas.head()

   Numero da loja Nome da loja          Cidade Estado Canal de vendas
0               1       Loja 1          Manaus     DF      E-commerce
1               2       Loja 2  Rio de Janeiro     MG      E-commerce
2               3       Loja 3  Belo Horizonte     AM      E-commerce
3               4       Loja 4          Manaus     CE     Loja Física
4               5       Loja 5  Rio de Janeiro     MG      E-commerce

In [15]:
df_produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Numero do produto     50 non-null     int64
 1   Nome do produto       50 non-null     object
 2   Categoria do produto  50 non-null     object
 3   Marca do produto      50 non-null     object
 4   Preco do produto      50 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 2.1+ KB

In [16]:
df_produtos.head()

,Numero do produto,Nome do produto,Categoria do produto,Marca do produto,Preco do produto
0,1,Produto 1,Brinquedo Educativo,Marca E,38.58
1,2,Produto 2,Carrinho,Marca B,34.21
2,3,Produto 3,Carrinho,Marca C,33.15
3,4,Produto 4,Carrinho,Marca A,31.94
4,5,Produto 5,Brinquedo Educativo,Marca C,79.41

In [17]:
# Mudar tipo da coluna
df_lojas["Numero da loja"] = df_lojas["Numero da loja"].astype(str)
df_produtos["Numero do produto"] = df_produtos["Numero do produto"].astype(str)
df["Numero da loja"] = df['Numero da loja'].astype(str)
df["Numero do produto"] = df["Numero do produto"].astype(str)

In [26]:
# Mesclando usando left join
df_vendas = df.merge(df_lojas, on="Numero da loja", how="left")
df_vendas = df_vendas.merge(df_produtos, on="Numero do produto", how='left')
df_vendas

,Numero da loja,Numero do produto,Mes da venda,Ano da venda,Quantidade vendida,Nome da loja,Cidade,Estado,Canal de vendas,Nome do produto,Categoria do produto,Marca do produto,Preco do produto
0,1,1,1,2021,47.0,Loja 1,Manaus,DF,E-commerce,Produto 1,Brinquedo Educativo,Marca E,38.58
1,1,2,1,2021,10.0,Loja 1,Manaus,DF,E-commerce,Produto 2,Carrinho,Marca B,34.21
2,1,3,1,2021,32.0,Loja 1,Manaus,DF,E-commerce,Produto 3,Carrinho,Marca C,33.15
3,1,4,1,2021,11.0,Loja 1,Manaus,DF,E-commerce,Produto 4,Carrinho,Marca A,31.94
4,1,5,1,2021,12.0,Loja 1,Manaus,DF,E-commerce,Produto 5,Brinquedo Educativo,Marca C,79.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,50,46,12,2022,10.0,Loja 50,Recife,AM,E-commerce,Produto 46,Brinquedo de Pelúcia,Marca D,26.01
59996,50,47,12,2022,23.0,Loja 50,Recife,AM,E-commerce,Produto 47,Brinquedo Educativo,Marca A,59.58
59997,50,48,12,2022,28.0,Loja 50,Recife,AM,E-commerce,Produto 48,Jogo de Tabuleiro,Marca D,82.88
59998,50,49,12,2022,6.0,Loja 50,Recife,AM,E-commerce,Produto 49,Brinquedo Educativo,Marca C,45.57
59999,50,50,12,2022,6.0,Loja 50,Recife,AM,E-commerce,Produto 50,Brinquedo Educativo,Marca B,76.28

In [27]:
# Deletando colunas desnecessarias 
df_vendas = df_vendas.drop(["Numero da loja", "Numero do produto"],axis=1)
df_vendas

,Mes da venda,Ano da venda,Quantidade vendida,Nome da loja,Cidade,Estado,Canal de vendas,Nome do produto,Categoria do produto,Marca do produto,Preco do produto
0,1,2021,47.0,Loja 1,Manaus,DF,E-commerce,Produto 1,Brinquedo Educativo,Marca E,38.58
1,1,2021,10.0,Loja 1,Manaus,DF,E-commerce,Produto 2,Carrinho,Marca B,34.21
2,1,2021,32.0,Loja 1,Manaus,DF,E-commerce,Produto 3,Carrinho,Marca C,33.15
3,1,2021,11.0,Loja 1,Manaus,DF,E-commerce,Produto 4,Carrinho,Marca A,31.94
4,1,2021,12.0,Loja 1,Manaus,DF,E-commerce,Produto 5,Brinquedo Educativo,Marca C,79.41
...,...,...,...,...,...,...,...,...,...,...,...
59995,12,2022,10.0,Loja 50,Recife,AM,E-commerce,Produto 46,Brinquedo de Pelúcia,Marca D,26.01
59996,12,2022,23.0,Loja 50,Recife,AM,E-commerce,Produto 47,Brinquedo Educativo,Marca A,59.58
59997,12,2022,28.0,Loja 50,Recife,AM,E-commerce,Produto 48,Jogo de Tabuleiro,Marca D,82.88
59998,12,2022,6.0,Loja 50,Recife,AM,E-commerce,Produto 49,Brinquedo Educativo,Marca C,45.57
59999,12,2022,6.0,Loja 50,Recife,AM,E-commerce,Produto 50,Brinquedo Educativo,Marca B,76.28

In [30]:
# Reordenando colunas 
df_vendas.columns
df_vendas = df_vendas[['Nome da loja','Cidade', 'Estado', 'Canal de vendas', 'Nome do produto',
                      'Categoria do produto', 'Marca do produto', 'Preco do produto',
                      'Mes da venda', 'Ano da venda', 'Quantidade vendida', ]]
df_vendas

,Nome da loja,Cidade,Estado,Canal de vendas,Nome do produto,Categoria do produto,Marca do produto,Preco do produto,Mes da venda,Ano da venda,Quantidade vendida
0,Loja 1,Manaus,DF,E-commerce,Produto 1,Brinquedo Educativo,Marca E,38.58,1,2021,47.0
1,Loja 1,Manaus,DF,E-commerce,Produto 2,Carrinho,Marca B,34.21,1,2021,10.0
2,Loja 1,Manaus,DF,E-commerce,Produto 3,Carrinho,Marca C,33.15,1,2021,32.0
3,Loja 1,Manaus,DF,E-commerce,Produto 4,Carrinho,Marca A,31.94,1,2021,11.0
4,Loja 1,Manaus,DF,E-commerce,Produto 5,Brinquedo Educativo,Marca C,79.41,1,2021,12.0
...,...,...,...,...,...,...,...,...,...,...,...
59995,Loja 50,Recife,AM,E-commerce,Produto 46,Brinquedo de Pelúcia,Marca D,26.01,12,2022,10.0
59996,Loja 50,Recife,AM,E-commerce,Produto 47,Brinquedo Educativo,Marca A,59.58,12,2022,23.0
59997,Loja 50,Recife,AM,E-commerce,Produto 48,Jogo de Tabuleiro,Marca D,82.88,12,2022,28.0
59998,Loja 50,Recife,AM,E-commerce,Produto 49,Brinquedo Educativo,Marca C,45.57,12,2022,6.0
59999,Loja 50,Recife,AM,E-commerce,Produto 50,Brinquedo Educativo,Marca B,76.28,12,2022,6.0

In [39]:
# Criar nova colunas a partir de outros valores 
df_vendas["Preco final"] = df_vendas["Quantidade vendida"] * df_vendas["Preco do produto"]
df_vendas

,Nome da loja,Cidade,Estado,Canal de vendas,Nome do produto,Categoria do produto,Marca do produto,Preco do produto,Mes da venda,Ano da venda,Quantidade vendida,Preco fimal,Preco final
0,Loja 1,Manaus,DF,E-commerce,Produto 1,Brinquedo Educativo,Marca E,38.58,1,2021,47.0,1813.26,1813.26
1,Loja 1,Manaus,DF,E-commerce,Produto 2,Carrinho,Marca B,34.21,1,2021,10.0,342.10,342.10
2,Loja 1,Manaus,DF,E-commerce,Produto 3,Carrinho,Marca C,33.15,1,2021,32.0,1060.80,1060.80
3,Loja 1,Manaus,DF,E-commerce,Produto 4,Carrinho,Marca A,31.94,1,2021,11.0,351.34,351.34
4,Loja 1,Manaus,DF,E-commerce,Produto 5,Brinquedo Educativo,Marca C,79.41,1,2021,12.0,952.92,952.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,Loja 50,Recife,AM,E-commerce,Produto 46,Brinquedo de Pelúcia,Marca D,26.01,12,2022,10.0,260.10,260.10
59996,Loja 50,Recife,AM,E-commerce,Produto 47,Brinquedo Educativo,Marca A,59.58,12,2022,23.0,1370.34,1370.34
59997,Loja 50,Recife,AM,E-commerce,Produto 48,Jogo de Tabuleiro,Marca D,82.88,12,2022,28.0,2320.64,2320.64
59998,Loja 50,Recife,AM,E-commerce,Produto 49,Brinquedo Educativo,Marca C,45.57,12,2022,6.0,273.42,273.42
59999,Loja 50,Recife,AM,E-commerce,Produto 50,Brinquedo Educativo,Marca B,76.28,12,2022,6.0,457.68,457.68

In [41]:
df_vendas

,Nome da loja,Cidade,Estado,Canal de vendas,Nome do produto,Categoria do produto,Marca do produto,Preco do produto,Mes da venda,Ano da venda,Quantidade vendida,Preco fimal,Preco final
0,Loja 1,Manaus,DF,E-commerce,Produto 1,Brinquedo Educativo,Marca E,38.58,1,2021,47.0,1813.26,1813.26
1,Loja 1,Manaus,DF,E-commerce,Produto 2,Carrinho,Marca B,34.21,1,2021,10.0,342.10,342.10
2,Loja 1,Manaus,DF,E-commerce,Produto 3,Carrinho,Marca C,33.15,1,2021,32.0,1060.80,1060.80
3,Loja 1,Manaus,DF,E-commerce,Produto 4,Carrinho,Marca A,31.94,1,2021,11.0,351.34,351.34
4,Loja 1,Manaus,DF,E-commerce,Produto 5,Brinquedo Educativo,Marca C,79.41,1,2021,12.0,952.92,952.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,Loja 50,Recife,AM,E-commerce,Produto 46,Brinquedo de Pelúcia,Marca D,26.01,12,2022,10.0,260.10,260.10
59996,Loja 50,Recife,AM,E-commerce,Produto 47,Brinquedo Educativo,Marca A,59.58,12,2022,23.0,1370.34,1370.34
59997,Loja 50,Recife,AM,E-commerce,Produto 48,Jogo de Tabuleiro,Marca D,82.88,12,2022,28.0,2320.64,2320.64
59998,Loja 50,Recife,AM,E-commerce,Produto 49,Brinquedo Educativo,Marca C,45.57,12,2022,6.0,273.42,273.42
59999,Loja 50,Recife,AM,E-commerce,Produto 50,Brinquedo Educativo,Marca B,76.28,12,2022,6.0,457.68,457.68

In [43]:
# Agrupando por colunas (e arredondar valor)
df_vendas.groupby(["Estado","Cidade"])["Preco final"].sum()

Estado  Cidade
AM      Belo Horizonte    1746359.95
        Manaus            1719090.27
        Recife            1704204.80
        São Paulo         3428776.60
BA      Curitiba          1728208.26
        Fortaleza         1734058.27
        São Paulo         1700174.28
CE      Belo Horizonte    1695695.76
        Curitiba          1690478.00
        Manaus            1746917.85
        Porto Alegre      1679288.69
        Recife            1704484.77
        Salvador          3333070.17
DF      Curitiba          1707738.22
        Fortaleza         1680698.06
        Manaus            3481280.78
        Rio de Janeiro    3418714.81
MG      Brasília          1664348.84
        Curitiba          1697819.16
        Porto Alegre      1693788.90
        Rio de Janeiro    3407087.09
PE      Belo Horizonte    1693180.96
        Brasília          1680054.77
        Fortaleza         1700334.69
        Manaus            3434215.71
        Salvador          1757922.53
        São Paulo         1741583.14
PR      Brasília          1661021.51
        Salvador          1710956.24
RJ      Belo Horizonte    5126226.82
        Brasília          1731424.00
        Porto Alegre      1682827.09
        Recife            1731703.71
RS      Fortaleza         1727131.69
        Manaus            1704423.48
        Porto Alegre      1701446.69
        Recife            1716037.61
        São Paulo         1692832.34
SP      Brasília          3447436.03
        Rio de Janeiro    1755993.05
        São Paulo         1769109.43
Name: Preco final, dtype: float64

In [45]:
# Agrupando por colunas (e arredondar valor)
df_vendas.groupby("Categoria do produto")[["Preco final","Quantidade vendida"]].sum()

                      Preco final  Quantidade vendida
Categoria do produto
Brinquedo Educativo   20707637.43            389309.0
Brinquedo de Pelúcia  12591673.55            238139.0
Carrinho              18376582.41            331751.0
Jogo de Tabuleiro     11147686.44            179601.0
Quebra-Cabeça         22704565.19            358620.0

In [47]:
# Tabela dinamica 
df_pivot = df_vendas.pivot_table(values="Preco final", index=["Canal de vendas", "Nome da loja"], columns="Mes da venda", aggfunc="sum")
df_pivot

Mes da venda                         1          2          3          4   \
Canal de vendas Nome da loja
E-commerce      Loja 1        158451.06  143137.00  142581.58  143074.33
                Loja 10       127497.56  134229.12  137326.63  139559.03
                Loja 11       142011.99  142398.11  141995.12  138941.68
                Loja 13       154243.17  150550.80  152875.49  139148.90
                Loja 16       138672.73  141178.30  151605.21  144674.27
                Loja 2        151713.53  133185.35  151740.59  134820.84
                Loja 22       144555.89  137174.91  143562.26  143222.62
                Loja 24       134845.11  149188.55  143119.46  144895.39
                Loja 26       153233.17  134711.86  127836.18  134217.10
                Loja 27       135620.92  159326.01  144717.04  133102.15
                Loja 28       153037.41  138860.70  151264.39  148571.53
                Loja 29       136602.60  148406.49  140743.12  133929.84
                Loja 3        151352.73  148993.38  137682.00  145475.02
                Loja 30       136207.88  153879.57  144658.49  141594.04
                Loja 31       157265.27  144025.88  153267.80  153417.07
                Loja 35       127743.32  153437.75  148160.56  151221.42
                Loja 39       153004.47  131240.53  139598.69  147312.19
                Loja 40       146806.12  130851.21  138347.72  142320.01
                Loja 42       147706.55  136822.04  146251.50  148756.41
                Loja 47       131793.38  128976.83  140079.02  133272.58
                Loja 49       130575.77  132392.53  135105.73  122773.51
                Loja 5        136923.54  146730.69  146302.76  125107.96
                Loja 50       134487.09  140221.37  151226.49  150229.74
                Loja 7        135698.10  148734.76  139910.91  149936.92
                Loja 9        139580.04  151354.61  139333.94  130035.36
Loja Física     Loja 12       147969.10  136154.27  142511.94  162405.42
                Loja 14       137592.25  135734.64  145329.95  135268.49
                Loja 15       151592.13  149212.22  159830.77  137906.54
                Loja 17       146957.47  145974.33  136128.48  149926.47
                Loja 18       149320.39  161547.19  154151.32  137900.22
                Loja 19       155839.91  153807.06  144730.79  145415.94
                Loja 20       141425.25  130324.04  161992.95  153015.34
                Loja 21       140715.25  143634.23  131113.06  140836.37
                Loja 23       147957.62  148553.70  147235.68  134917.72
                Loja 25       149127.57  143329.36  142277.11  135033.74
                Loja 32       149052.91  159860.09  145101.71  149612.83
                Loja 33       149167.63  137214.91  138413.09  136362.21
                Loja 34       140368.00  132072.66  144446.73  132040.19
                Loja 36       137339.20  133999.15  124725.47  132309.30
                Loja 37       147823.71  132999.38  149756.72  152568.44
                Loja 38       132055.19  128118.59  141832.38  152498.54
                Loja 4        137467.34  151683.99  136812.80  142637.10
                Loja 41       140820.59  155348.06  143194.52  154388.50
                Loja 43       165739.45  149481.85  147286.76  134378.66
                Loja 44       123189.78  154888.55  148888.20  136113.36
                Loja 45       147365.82  147478.83  137528.66  139364.51
                Loja 46       144413.65  144570.64  141778.67  131984.00
                Loja 48       150360.17  136186.15  149122.02  146353.10
                Loja 6        136095.18  141673.58  133453.77  143534.23
                Loja 8        129858.67  150316.02  138386.47  146951.38

Mes da venda                         5          6          7          8   \
Canal de vendas Nome da loja
E-commerce      Loja 1        150642.35  129684.87  134673.59  155945.42
                Loja 10       150284.73  130590.07  142119.20  146954.21
                Loja 11       138882.67  134059.95  147185.60  149615.76
                Loja 13       145762.77  137346.24  137432.53  127660.67
                Loja 16       155080.35  132897.06  142632.98  158306.89
                Loja 2        134080.73  158163.02  145186.11  145492.42
                Loja 22       159178.72  142279.89  144589.42  129592.65
                Loja 24       136123.53  141902.58  139513.03  146076.08
                Loja 26       135434.86  139702.99  154947.69  138024.60
                Loja 27       141491.88  134985.81  128671.12  143429.16
                Loja 28       157449.87  110384.76  132789.12  142684.63
                Loja 29       149104.81  141171.84  148460.96  140155.88
                Loja 3        143010.60  149312.57  143408.22  145466.75
                Loja 30       141687.61  145370.59  147269.60  149681.39
                Loja 31       136333.78  141970.86  153502.32  133537.95
                Loja 35       135147.03  143929.46  143624.55  137148.10
                Loja 39       130385.31  133182.33  129788.69  136936.17
                Loja 40       149993.80  140226.24  149545.93  153732.35
                Loja 42       146275.50  144487.22  134099.90  143960.62
                Loja 47       146186.76  139074.17  119140.89  137077.28
                Loja 49       154341.40  146563.04  127295.30  147276.79
                Loja 5        126928.64  142063.56  133189.72  157800.08
                Loja 50       140174.44  124470.33  144492.48  147696.70
                Loja 7        138486.10  153011.88  149587.76  168306.01
                Loja 9        142262.05  125488.23  142332.88  132100.53
Loja Física     Loja 12       133258.92  144144.12  148243.96  144158.26
                Loja 14       144847.88  139788.60  147786.05  132866.29
                Loja 15       138634.41  141081.56  155104.85  148900.54
                Loja 17       136308.24  136618.66  150554.35  156862.84
                Loja 18       138621.89  127784.01  141954.34  135144.34
                Loja 19       153974.41  138593.68  131185.58  145126.09
                Loja 20       143266.52  158840.16  138107.11  147135.87
                Loja 21       155574.45  142610.92  147109.20  140174.82
                Loja 23       145312.93  145711.99  134431.27  132338.63
                Loja 25       133900.40  149210.71  140176.66  148122.60
                Loja 32       147579.77  136205.58  139639.62  138260.01
                Loja 33       151609.85  146046.20  138209.33  159101.00
                Loja 34       126813.71  122967.03  147321.13  133981.51
                Loja 36       125168.97  148843.77  147286.13  144108.10
                Loja 37       138801.28  130554.35  133752.90  145427.87
                Loja 38       157422.65  138548.20  150091.66  145423.90
                Loja 4        158591.60  132398.23  157133.38  129415.45
                Loja 41       153150.45  132297.41  135595.19  156957.94
                Loja 43       143382.05  135845.01  156130.25  145266.55
                Loja 44       147813.04  149826.14  150375.21  139561.63
                Loja 45       132019.80  142383.22  146455.93  147944.66
                Loja 46       149836.51  130487.31  138058.87  147715.85
                Loja 48       146644.74  128804.87  138541.38  158609.90
                Loja 6        150960.09  135635.66  132965.00  150257.45
                Loja 8        144315.74  147608.32  146077.64  144541.15

Mes da venda                         9          10         11         12
Canal de vendas Nome da loja
E-commerce      Loja 1        150316.82  141932.10  146307.99  135361.05
                Loja 10       151391.04  141846.89  132261.03  149923.20
                Loja 11       140778.01  152179.38  134671.70  117978.09
                Loja 13       124612.41  147017.47  136720.33  126683.99
                Loja 16       141920.71  152496.16  146554.96  143153.00
                Loja 2        150563.31  154927.64  138545.16  142642.38
                Loja 22       154706.85  154150.71  127313.49  154404.69
                Loja 24       139659.11  136627.79  145486.67  147047.47
                Loja 26       148198.90  132303.52  140250.98  151616.15
                Loja 27       126396.51  142009.05  149179.30  156766.81
                Loja 28       155257.09  143640.01  133225.39  138767.13
                Loja 29       148877.11  139118.26  154611.22  135385.55
                Loja 3        153857.23  140730.85  144880.48  142190.12
                Loja 30       147809.24  152634.49  153002.44  147583.63
                Loja 31       146972.31  140876.78  147512.49  147310.54
                Loja 35       146655.23  145898.62  148851.42  125920.76
                Loja 39       132103.08  134926.49  146124.60  146418.96
                Loja 40       142555.26  131907.41  139686.27  131846.84
                Loja 42       141689.34  146002.50  132255.76  133139.35
                Loja 47       156496.41  148195.43  140051.18  144004.91
                Loja 49       140119.92  151518.00  139160.42  159318.30
                Loja 5        136533.84  139935.49  141644.95  132864.78
                Loja 50       133639.49  144214.44  142702.22  150650.01
                Loja 7        155980.82  144059.94  156973.06  128423.17
                Loja 9        138100.35  143511.75  141031.81  154157.14
Loja Física     Loja 12       139569.93  133565.36  133831.01  162395.97
                Loja 14       144418.23  148974.82  138665.00  149062.49
                Loja 15       137288.58  131852.58  141827.75  133899.76
                Loja 17       151854.35  145596.90  139979.27  161161.17
                Loja 18       149198.43  155173.15  144943.39  123351.60
                Loja 19       148884.87  136200.14  131665.60  147673.61
                Loja 20       134164.68  136472.22  129794.74  153744.80
                Loja 21       128591.42  131249.68  161119.76  141694.32
                Loja 23       146072.75  141377.68  152267.48  155246.55
                Loja 25       139730.66  140529.70  139304.60  150213.13
                Loja 32       143807.43  146853.47  136114.08  145998.57
                Loja 33       128282.20  133940.82  140983.46  133850.26
                Loja 34       140706.65  129750.61  130037.00  135997.27
                Loja 36       155398.59  149119.50  153838.28  138554.07
                Loja 37       150508.63  150903.00  134950.40  147990.93
                Loja 38       146034.68  130959.17  135208.14  148495.33
                Loja 4        159591.58  138215.32  148141.41  154829.65
                Loja 41       135753.97  152997.90  135347.14  145731.47
                Loja 43       133779.57  141639.53  130571.92  148202.11
                Loja 44       145434.89  147539.33  143986.85  146441.29
                Loja 45       152949.60  133557.72  129373.39  137366.76
                Loja 46       148996.37  128811.77  137188.75  138984.70
                Loja 48       133303.52  145546.32  133453.19  125906.98
                Loja 6        120504.00  139515.03  143308.31  158154.76
                Loja 8        144845.33  128364.62  138907.49  140001.45